export { default as HomePage } from './HomePage/HomePage'
export { default as SoldiersPage } from './SoldiersPage/SoldiersPage'
export { default as ValorsPage } from './ValorsPage/ValorsPage'
export { default as PhotosPage } from './PhotosPage/PhotosPage'
export { default as NotFoundPage } from './NotFoundPage/NotFoundPage'